// TEMPORARY MOCK DATA
// Replace these arrays with Firestore reads once Firebase is wired up
// (e.g. collections: projects, ideas, thinking, travels, plans).
// Shapes match lib/types.ts so the swap should be close to drop-in.

import { Project, Idea, ThinkingPost, Trip, Goal } from "./types";

export const projects: Project[] = [
  {
    slug: "predict-me",
    title: "Predict-Me",
    short: "A machine learning app that predicts outcomes from user-provided data.",
    category: "Game",
    imageUrl: "/predict me.png",
    technologies: ["Python", "scikit-learn", "Flask"],
    status: "completed",
    featured: true,
    problem: "People without a data science background have no simple way to run predictive models on their own data.",
    ideaText: "Build a lightweight interface where a dataset goes in and a trained model, with plain-language results, comes out.",
    howItWorks: "The app cleans the uploaded dataset, trains a model against the target column, and reports predictions with accuracy metrics.",
    features: ["CSV upload and cleaning", "Model training with scikit-learn", "Plain-language result summaries"],
    challenges: "Handling messy, inconsistent real-world data without asking the user to pre-clean it themselves.",
    learned: "How much of a machine learning project is data preparation, not modeling.",
    future: "Support more model types and let users compare them side by side.",
    github: "",
    demo: "https://aashfaak.github.io/Predict-Me/",
  },
  {
    slug: "neon-flappy-game",
    title: "Neon Flappy Game",
    short: "A colorful arcade side-scroller inspired by the classic flappy gameplay loop.",
    category: "Game",
    imageUrl: "/Neon-Flappy.png",
    technologies: ["JavaScript", "HTML5", "CSS", "Canvas"],
    status: "completed",
    featured: true,
    problem: "Simple browser games are often either too basic or too hard to play casually on a single page.",
    ideaText: "Create a lightweight, polished arcade game with fast controls and satisfying rhythm gameplay.",
    howItWorks: "The player taps or clicks to flap through gaps while the game continuously scrolls obstacles and tracks score.",
    features: ["Responsive controls", "Neon visual design", "Score tracking and replay flow"],
    challenges: "Balancing difficulty and responsiveness so the game feels fun without becoming frustrating too quickly.",
    learned: "How small timing decisions impact the feel of a game more than large feature count does.",
    future: "Add sound effects, mobile touch polish, and a high-score system.",
    github: "",
    demo: "https://aashfaak.github.io/Neon-Flappy-Game/",
  },
  {
    slug: "neon-snake-game",
    title: "Neon Snake Game",
    short: "A neon-styled snake game built for quick, addictive gameplay in the browser.",
    category: "Game",
    imageUrl: "/Snake Game.png",
    technologies: ["JavaScript", "HTML5", "CSS", "Canvas"],
    status: "completed",
    featured: true,
    problem: "Classic arcade games are easy to recreate, but a clean modern version still needs careful design and polish.",
    ideaText: "Build a crisp, playable browser game that feels vibrant, smooth, and immediately familiar.",
    howItWorks: "The snake moves continuously, consumes items, grows in length, and the player avoids collision with walls and itself.",
    features: ["Keyboard controls", "Neon effects and UI", "Score progression and restart flow"],
    challenges: "Keeping movement smooth and collision logic reliable while preserving the original game feel.",
    learned: "How arcade mechanics become much more satisfying when movement and feedback are tuned well.",
    future: "Add obstacle levels, difficulty modes, and a leaderboard experience.",
    github: "",
    demo: "https://aashfaak.github.io/Neon-Snake-Game/",
  },

  {
    slug: "tanim-intesar-portfolio",
    title: "Tanim Intesar Portfolio",
    short: "Personal portfolio and journal website built with Next.js, Firebase, and Cloudinary.",
    category: "Portfolio Web App",
    imageUrl: "/tanim intesar.png",
    technologies: ["Next.js", "Firebase", "Cloudinary", "TypeScript"],
    status: "completed",
    featured: true,
    problem: "A personal portfolio needs a clean structure, easy updates, and a polished presentation for projects, thoughts, and travel notes.",
    ideaText: "Create a personal portfolio and journal that combines professional projects, ideas, and writing in one modern web experience.",
    howItWorks: "The site gathers curated content from structured data and presents it as a polished collection of portfolio sections and journal entries.",
    features: ["Portfolio sections", "Journal and project pages", "Cloudinary media support"],
    challenges: "Keeping content flexible enough for portfolio updates while maintaining a consistent visual design.",
    learned: "How portfolio architecture and content modeling affect long-term maintainability.",
    future: "Add richer CMS editing, analytics, and more curated project sections.",
    github: "https://github.com/aashfaak/tanim-intesar-portfolio",
    demo: "https://tanimintesar.vercel.app/",
  },
  {
    slug: "house-booking",
    title: "House Booking App",
    short: "A booking platform for finding and reserving rental homes.",
    category: "App Development",
   
    technologies: ["Laravel", "MySQL", "Bootstrap"],
    status: "completed",
    featured: true,
    problem: "Small property owners lack an easy way to list homes and manage bookings online.",
    ideaText: "A straightforward booking site: list a property, set availability, accept reservations.",
    howItWorks: "Owners create listings with photos and pricing; visitors browse, check availability, and submit booking requests.",
    features: ["Property listings with search/filter", "Availability calendar", "Booking request workflow"],
    challenges: "Modeling availability and preventing double-bookings cleanly in the database.",
    learned: "How to design a relational schema for a real booking system, not just a CRUD app.",
    future: "Add payments and owner-side analytics.",
    github: "https://github.com/aashfaak/House-Booking-pp",
    demo: "",
  },
  {
    slug: "gesture-control",
    title: "Real-Time Gesture Control",
    short: "Computer vision system that controls actions using hand gestures.",
    category: "AI / Computer Vision",
     imageUrl: "/Hand Gesture.webp",
    technologies: ["Python", "OpenCV", "MediaPipe"],
    status: "completed",
    featured: true,
    problem: "Touchless control is useful in many contexts but usually requires expensive hardware.",
    ideaText: "Use nothing but a webcam and hand-tracking to translate gestures into real-time commands.",
    howItWorks: "MediaPipe tracks hand landmarks per frame; specific landmark patterns are mapped to actions.",
    features: ["Real-time hand landmark tracking", "Custom gesture-to-action mapping", "Works with a standard webcam"],
    challenges: "Keeping detection stable and low-latency without specialized hardware.",
    learned: "Practical constraints of real-time computer vision — frame rate, lighting, and false positives.",
    future: "Expand the gesture vocabulary and package it as a reusable library.",
    github: "https://github.com/aashfaak/Hand-Gesture",
    demo: "",
  },
  {
    slug: "big-data-hadoop",
    title: "Big Data Analysis / Hadoop",
    short: "Coursework project processing large datasets with Hadoop and Pig.",
    category: "Data Analysis",
    imageUrl: "/bigdata.webp",
    technologies: ["Hadoop", "Pig", "HDFS"],
    status: "completed",
    featured: false,
    problem: "Traditional tools break down once a dataset no longer fits comfortably in memory.",
    ideaText: "Work directly with the Hadoop ecosystem to process a large dataset in a distributed way.",
    howItWorks: "Data is stored in HDFS and processed with Pig scripts, distributing work across nodes.",
    features: ["HDFS storage setup", "Pig scripts for data transformation", "Distributed processing pipeline"],
    challenges: "Thinking in terms of distributed jobs instead of a single sequential script.",
    learned: "What Hadoop actually solves, and when a distributed system is worth the added complexity.",
    future: "Revisit the same problem with Spark for comparison.",
    github: "https://github.com/aashfaak/IMDB-Movies-Data-Analysis",
    demo: "",
  },
  {
    slug: "bus-ticket-reservation",
    title: "Bus Ticket Reservation",
    short: "A system for browsing routes, selecting seats, and booking bus tickets.",
    category: "Web Development",
    imageUrl: "/bus.webp",
    technologies: ["PHP", "MySQL", "JavaScript"],
    status: "completed",
    featured: false,
    problem: "Many local bus operators still handle reservations manually or over the phone.",
    ideaText: "A simple reservation system: pick a route, pick a seat, confirm a booking.",
    howItWorks: "Routes and seat maps are stored in the database; a booking locks the selected seat for that trip.",
    features: ["Route and schedule browsing", "Interactive seat selection", "Booking confirmation"],
    challenges: "Preventing two people from booking the same seat at the same time.",
    learned: "Why booking systems need careful handling of concurrent writes.",
    future: "Add an admin view for operators to manage routes and schedules.",
    github: "https://github.com/aashfaak/SDP_BTRS_main",
    demo: "",
  },
  
];

export const ideas: Idea[] = [
  {
    slug: "local-services-marketplace",
    title: "A platform for local skilled services",
    what: "A marketplace connecting people who need small jobs done with local skilled workers.",
    why: "Finding a reliable electrician or tutor nearby is still mostly word of mouth.",
    problem: "Discovery and trust — knowing who's available, nearby, and actually good.",
    who: "Households and small businesses needing services, and workers looking for steady local work.",
    how: "Location-based listings, simple booking, and a review system built on completed jobs.",
    status: "idea",
  },
  {
    slug: "study-group-matcher",
    title: "Study group matching for university courses",
    what: "A tool that matches students in the same course into small study groups automatically.",
    why: "Most students want to study together but never find the right group organically.",
    problem: "Coordinating schedules and skill levels across a large class.",
    who: "University students, starting with CSE courses at Premier University.",
    how: "Students submit availability and topics; a simple matching algorithm forms groups each week.",
    status: "researching",
  },
];

export const thinking: ThinkingPost[] = [
  {
    slug: "what-hadoop-taught-me",
    title: "What Hadoop taught me about large datasets",
    excerpt: "Distributed processing sounds abstract until you actually watch a job split across nodes.",
    date: "2026-03-01",
    category: "Data",
  },
  {
    slug: "first-android-app-lessons",
    title: "What I learned building my first Android app",
    excerpt: "The gap between a working demo and something you'd actually ship is bigger than it looks.",
    date: "2026-01-14",
    category: "Mobile",
  },
  {
    slug: "why-python-seriously",
    title: "Why I started learning Python seriously",
    excerpt: "It started as the language for one assignment and became the one I reach for by default.",
    date: "2025-11-02",
    category: "Learning",
  },
];

export const trips: Trip[] = [
  {
    slug: "weekend-in-bandarban",
    title: "A Weekend in Bandarban",
    location: "Bandarban, Bangladesh",
    date: "2026-02",
    excerpt: "Hill roads, a quiet lake, and the kind of silence you don't get in Chattogram.",
  },
];

export const goals: Goal[] = [
  { title: "Learn Big Data Analytics", progress: 40, category: "Learning" },
  { title: "Build this portfolio", progress: 70, category: "Project" },
  { title: "Build a startup idea", progress: 25, category: "Long-term" },
];
